language: objective-c
osx_image: xcode11.2

branches:
  except:
    - localization

env:
  global:
    - THEOS=theos

script:
- make package

before_install:
- gem install xcpretty
- brew install ldid
- git clone --recursive https://github.com/theos/theos.git $THEOS
