name: Build Zebra

on:
  push:
    branches:
      - master
  

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        brew install ldid
        git clone --recursive https://github.com/theos/theos.git theos
        
    - name: Build Package
      run: make package
